image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - cd sources/Batch/it.ifitalia.batch.accorpamentoFileFIS.build
    - mvn $MAVEN_CLI_OPTS compile -P bnl

test:
  stage: test
  script:
    - cd sources/Batch/it.ifitalia.batch.accorpamentoFileFIS.build
    - mvn $MAVEN_CLI_OPTS test -P bnl

deploy:
  stage: deploy
  script:
    - cd sources/Batch/it.ifitalia.batch.accorpamentoFileFIS.build
    - mvn $MAVEN_CLI_OPTS deploy -P bnl
  only:
    - devolop